// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        ias_kotlin_version = "1.9.0"
        ias_gradle_version = "8.1.2"
        ias_gradle_plugin_version = "1.8.10"
        ias_inappstory_version = "d8ac2642ae17689f20b7d783351ff38349ec0088"
        ias_fragment_ktx = "1.8.9"
        ias_appcompat = "1.5.0"
        ias_material = "1.6.1"
        ias_activity_compose = "1.5.0"
        ias_compose_bom = "2023.03.00"
        inappstory_compose_output_version = "0.0.5"
        inappstory_compose_output_build = 2
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$ias_gradle_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$ias_gradle_plugin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}